### ISSUE TITLE
点进来咋跟hexo主题不一样啊

### ISSUE THREAD

**Issue by plzthxup** [WinMin/Sw-blog#5]
https://bestwing.me/  大大现在这个主题能分享一下吗，简洁又很酷

**Comment by winmin** [comment]
probberechts/hexo-theme-cactus: A responsive, clean and simple theme for
Hexo. (github.com) <https://github.com/probberechts/hexo-theme-cactus>

这个吗

plzthxup ***@***.***> 于2021年10月30日周六 下午6:56写道：
